//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alert {
            get {
                object obj = ResourceManager.GetObject("alert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ProgramFormatter xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Rules&gt;
        ///    &lt;ProgramFormatRule Number=&quot;1&quot; Instruction=&quot;CollisionReqKrc2&quot; SelectedAction=&quot;RemoveCommand&quot; GroupItems=&quot;false&quot; /&gt;
        ///    &lt;ProgramFormatRule Number=&quot;2&quot; Instruction=&quot;PLC_COM&quot; SelectedAction=&quot;EnterBefore&quot; GroupItems=&quot;true&quot; /&gt;
        ///  &lt;/Rules&gt;
        ///  &lt;Instructions&gt;
        ///    &lt;KukaInstruction Name=&quot;CollisionReqKrc2&quot; IsComment=&quot;true&quot; IsFold=&quot;true&quot; KeyWordsSt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProgramFormatter {
            get {
                return ResourceManager.GetString("ProgramFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ProjectInfos xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Project Name=&quot;G7x&quot; RobotType=&quot;KUKA&quot;&gt;
        ///    &lt;TypNumbers&gt;
        ///      &lt;TypNumber Number=&quot;1&quot; Name=&quot;werwerewrw&quot; /&gt;
        ///      &lt;TypNumber Number=&quot;10&quot; Name=&quot;G70&quot; /&gt;
        ///      &lt;TypNumber Number=&quot;11&quot; Name=&quot;G71&quot; /&gt;
        ///    &lt;/TypNumbers&gt;
        ///    &lt;TypIDMain Value=&quot;41&quot; /&gt;
        ///    &lt;TypIDCommunal Value=&quot;42&quot; /&gt;
        ///	&lt;ApplicationTypes&gt;
        ///		&lt;SpotType A04=&quot;true&quot; A05=&quot;false&quot;/&gt;
        ///		&lt;GlueType A08=&quot;true&quot; B08=&quot;false&quot;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectInfos {
            get {
                return ResourceManager.GetString("ProjectInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tick {
            get {
                object obj = ResourceManager.GetObject("tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
