//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobKalDat {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RobKalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RobKalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobKalDat.RobKalResources", typeof(RobKalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Messprotokoll_template {
            get {
                object obj = ResourceManager.GetObject("Messprotokoll_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project&gt;
        ///  &lt;Basic Company=&quot;&quot; Creater=&quot;&quot; Zone=&quot;&quot; Station=&quot;&quot; ReportPath=&quot;&quot; ReportName=&quot;&quot; LastModified=&quot;&quot; /&gt;
        ///  &lt;Settings XLim=&quot;10&quot; YLim=&quot;10&quot; ZLim=&quot;10&quot; RXLim=&quot;1&quot; RYLim=&quot;1&quot; RZLim=&quot;1&quot; ToleranceX=&quot;25&quot; ToleranceY=&quot;25&quot; ToleranceZ=&quot;25&quot; ToleranceRX=&quot;1.000000&quot; ToleranceRY=&quot;1.000000&quot; ToleranceRZ=&quot;1.000000&quot; CheckBaseToleranceX=&quot;1&quot; CheckBaseToleranceY=&quot;1&quot; CheckBaseToleranceZ=&quot;1&quot; CheckBaseToleranceRX=&quot;0.100000&quot; CheckBaseToleranceRY=&quot;0.100000&quot; CheckBaseToleranceRZ=&quot;0.100000&quot; CheckW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string templateBase {
            get {
                return ResourceManager.GetString("templateBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///  &lt;KUKARoboter.SafeRobot.Parameters&gt;
        ///    &lt;encryptedData&gt;
        ///      &lt;SafetyParameters&gt;
        ///        &lt;RangeMonitoring&gt;
        ///        &lt;/RangeMonitoring&gt;
        ///        &lt;Tools&gt;
        ///        &lt;/Tools&gt;
        ///      &lt;/SafetyParameters&gt;
        ///    &lt;/encryptedData&gt;
        ///  &lt;/KUKARoboter.SafeRobot.Parameters&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string templateSafetyKuka {
            get {
                return ResourceManager.GetString("templateSafetyKuka", resourceCulture);
            }
        }
    }
}
