//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotFilesEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotFilesEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Icon podobny do zasobu (Ikona).
        /// </summary>
        internal static System.Drawing.Icon Harvester {
            get {
                object obj = ResourceManager.GetObject("Harvester", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu /PROG  PROG{ProgNum}
        ////ATTR
        ///OWNER		= MNEDITOR;
        ///COMMENT		= &quot;&quot;;
        ///PROG_SIZE	= 0;
        ///CREATE		= DATE {Date}  TIME {Time};
        ///MODIFIED	= DATE {Date}  TIME {Time};
        ///FILE_NAME	= ;
        ///VERSION		= 0;
        ///LINE_COUNT	= 0;
        ///MEMORY_SIZE	= 0;
        ///PROTECT		= READ_WRITE;
        ///TCD:  STACK_SIZE	= 0,
        ///      TASK_PRIORITY	= 50,
        ///      TIME_SLICE	= 0,
        ///      BUSY_LAMP_OFF	= 0,
        ///      ABORT_REQUEST	= 0,
        ///      PAUSE_REQUEST	= 0;
        ///DEFAULT_GROUP	= 1,*,*,*,*;
        ///CONTROL_CODE	= 00000000 00000000;
        ////APPL
        ///
        ///CORNER_SPEED_HEADER;
        ///  ENABLE_CORNER_SPEED  [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string ProgHeaderFanucDE {
            get {
                return ResourceManager.GetString("ProgHeaderFanucDE", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu /PROG  PROG{ProgNum}
        ////ATTR
        ///OWNER		= MNEDITOR;
        ///COMMENT		= &quot;&quot;;
        ///PROG_SIZE	= 0;
        ///CREATE		= DATE {Date}  TIME {Time};
        ///MODIFIED	= DATE {Date}  TIME {Time};
        ///FILE_NAME	= ;
        ///VERSION		= 0;
        ///LINE_COUNT	= 0;
        ///MEMORY_SIZE	= 0;
        ///PROTECT		= READ_WRITE;
        ///TCD:  STACK_SIZE	= 0,
        ///      TASK_PRIORITY	= 50,
        ///      TIME_SLICE	= 0,
        ///      BUSY_LAMP_OFF	= 0,
        ///      ABORT_REQUEST	= 0,
        ///      PAUSE_REQUEST	= 0;
        ///DEFAULT_GROUP	= 1,*,*,*,*;
        ///CONTROL_CODE	= 00000000 00000000;
        ////APPL
        ///
        ///CORNER_SPEED_HEADER;
        ///  ENABLE_CORNER_SPEED  [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string ProgHeaderFanucEN {
            get {
                return ResourceManager.GetString("ProgHeaderFanucEN", resourceCulture);
            }
        }
    }
}
